from docx import Document
from docx.shared import Inches

document = Document()


table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Views:"
row_cells = table.add_row().cells
row_cells[0].text = str("Files:")
row_cells = table.add_row().cells
row_cells[0].text = str("items.txt")
row_cells = table.add_row().cells
row_cells[0].text = str("attributes.txt")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=2)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Group"
hdr_cells[1].text = "Dimensions"
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=2)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Name"
hdr_cells[1].text = "External Type"
row_cells = table.add_row().cells
row_cells[0].text = str("Price Range")
row_cells[1].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("Endeca")
row_cells[1].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("Brand")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("New")
row_cells[1].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("Free Shipping")
row_cells[1].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("On Sale")
row_cells[1].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("Season")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Sports")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Accessory Type")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Height")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Skin Type")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Weight")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Collection")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Color")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Gender")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Occasion")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Type")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Virtual Bear")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Exclusive")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Brand")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Season")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Sports")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Accessory Type")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Height")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Skin Type")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Weight")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Collection")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Color")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Gender")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Occasion")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Type")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Virtual Bear")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells
row_cells[0].text = str("Exclusive")
row_cells[1].text = str("AUTOGEN")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=3)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Manipulator Name"
hdr_cells[1].text = "Record Source"
hdr_cells[2].text = "Manipulations"
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=2)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Name"
hdr_cells[1].text = "Type"
row_cells = table.add_row().cells
row_cells[0].text = str("p_url_detail")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_description_short")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_image")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_keyword")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_name")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_price_retail")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_unique_id")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_price_sale")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_price_sort")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sku")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_brand")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_description_long")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_default")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_rating")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_new")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_on_sale")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_free_shipping")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_category_id")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_group_id")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_alpha_1")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_alpha_2")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_alpha_3")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_alpha_4")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_alpha_5")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_integer_1")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_integer_2")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_integer_3")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_integer_4")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_integer_5")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_float_1")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_float_2")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_float_3")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_float_4")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_float_5")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_1")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_2")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_3")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_4")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_5")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_6")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_7")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_8")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_9")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_search_alpha_0")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_alpha_0")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_float_0")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sort_integer_0")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_custom_0")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_custom_1")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_custom_2")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_custom_3")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_custom_4")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_custom_5")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_upc")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_total_units_sold")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_profit_margin")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_profit_dollars")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_sales_velocity")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_total_detail_views")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_pct_conversion")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_days_added")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_inventory")
row_cells[1].text = str("INTEGER")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_pct_on_sale")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_pct_bounceback")
row_cells[1].text = str("FLOATING POINT")
row_cells = table.add_row().cells
row_cells[0].text = str("p_large_image")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells
row_cells[0].text = str("p_small_image")
row_cells[1].text = str("ALPHA")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=4)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Source"
hdr_cells[1].text = "Target"
hdr_cells[2].text = "Target Type"
hdr_cells[3].text = "Match Mode"
row_cells = table.add_row().cells
row_cells[0].text = str("P_Endeca")
row_cells[1].text = str("Endeca")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("brand")
row_cells[1].text = str("p_brand")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("description_long")
row_cells[1].text = str("p_description_long")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("description_short")
row_cells[1].text = str("p_description_short")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("image")
row_cells[1].text = str("p_image")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_free_shipping")
row_cells[1].text = str("p_is_free_shipping")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_new")
row_cells[1].text = str("p_is_new")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_on_sale")
row_cells[1].text = str("p_is_on_sale")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("keyword")
row_cells[1].text = str("p_keyword")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("name")
row_cells[1].text = str("p_name")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("price_retail")
row_cells[1].text = str("p_price_retail")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("price_sale")
row_cells[1].text = str("p_price_sale")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("price_sort")
row_cells[1].text = str("p_price_sort")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sku")
row_cells[1].text = str("p_sku")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_default")
row_cells[1].text = str("p_sort_default")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_rating")
row_cells[1].text = str("p_sort_rating")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("unique_id")
row_cells[1].text = str("p_unique_id")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("url_detail")
row_cells[1].text = str("p_url_detail")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("brand")
row_cells[1].text = str("Brand")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("category_id")
row_cells[1].text = str("Category")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("category_id")
row_cells[1].text = str("p_category_id")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_free_shipping")
row_cells[1].text = str("Free Shipping")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("is_new")
row_cells[1].text = str("New")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("is_on_sale")
row_cells[1].text = str("On Sale")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("price_sort")
row_cells[1].text = str("Price Range")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("NORMAL")
row_cells = table.add_row().cells
row_cells[0].text = str("group_id")
row_cells[1].text = str("p_group_id")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_custom_0")
row_cells[1].text = str("p_is_custom_0")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_custom_1")
row_cells[1].text = str("p_is_custom_1")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_custom_2")
row_cells[1].text = str("p_is_custom_2")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_custom_3")
row_cells[1].text = str("p_is_custom_3")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_custom_4")
row_cells[1].text = str("p_is_custom_4")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("is_custom_5")
row_cells[1].text = str("p_is_custom_5")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_days_added")
row_cells[1].text = str("p_metric_days_added")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_inventory")
row_cells[1].text = str("p_metric_inventory")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_pct_bounceback")
row_cells[1].text = str("p_metric_pct_bounceback")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_pct_conversion")
row_cells[1].text = str("p_metric_pct_conversion")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_pct_on_sale")
row_cells[1].text = str("p_metric_pct_on_sale")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_profit_dollars")
row_cells[1].text = str("p_metric_profit_dollars")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_profit_margin")
row_cells[1].text = str("p_metric_profit_margin")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_sales_velocity")
row_cells[1].text = str("p_metric_sales_velocity")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_total_detail_views")
row_cells[1].text = str("p_metric_total_detail_views")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("metric_total_units_sold")
row_cells[1].text = str("p_metric_total_units_sold")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_0")
row_cells[1].text = str("p_search_alpha_0")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_1")
row_cells[1].text = str("p_search_alpha_1")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_2")
row_cells[1].text = str("p_search_alpha_2")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_3")
row_cells[1].text = str("p_search_alpha_3")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_4")
row_cells[1].text = str("p_search_alpha_4")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_5")
row_cells[1].text = str("p_search_alpha_5")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_6")
row_cells[1].text = str("p_search_alpha_6")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_7")
row_cells[1].text = str("p_search_alpha_7")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_8")
row_cells[1].text = str("p_search_alpha_8")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("search_alpha_9")
row_cells[1].text = str("p_search_alpha_9")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_alpha_0")
row_cells[1].text = str("p_sort_alpha_0")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_alpha_1")
row_cells[1].text = str("p_sort_alpha_1")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_alpha_2")
row_cells[1].text = str("p_sort_alpha_2")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_alpha_3")
row_cells[1].text = str("p_sort_alpha_3")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_alpha_4")
row_cells[1].text = str("p_sort_alpha_4")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_alpha_5")
row_cells[1].text = str("p_sort_alpha_5")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_float_0")
row_cells[1].text = str("p_sort_float_0")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_float_1")
row_cells[1].text = str("p_sort_float_1")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_float_2")
row_cells[1].text = str("p_sort_float_2")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_float_3")
row_cells[1].text = str("p_sort_float_3")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_float_4")
row_cells[1].text = str("p_sort_float_4")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_float_5")
row_cells[1].text = str("p_sort_float_5")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_integer_0")
row_cells[1].text = str("p_sort_integer_0")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_integer_1")
row_cells[1].text = str("p_sort_integer_1")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_integer_2")
row_cells[1].text = str("p_sort_integer_2")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_integer_3")
row_cells[1].text = str("p_sort_integer_3")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_integer_4")
row_cells[1].text = str("p_sort_integer_4")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("sort_integer_5")
row_cells[1].text = str("p_sort_integer_5")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("accessorySeason")
row_cells[1].text = str("Season")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("accessorySports")
row_cells[1].text = str("Sports")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("accessoryType")
row_cells[1].text = str("Accessory Type")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("animalHeight")
row_cells[1].text = str("Height")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("animalSkinType")
row_cells[1].text = str("Skin Type")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("animalWeight")
row_cells[1].text = str("Weight")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("collection")
row_cells[1].text = str("Collection")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("color")
row_cells[1].text = str("Color")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("gender")
row_cells[1].text = str("Gender")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("occasion")
row_cells[1].text = str("Occasion")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("type")
row_cells[1].text = str("Type")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("virtualBearSubtype")
row_cells[1].text = str("Virtual Bear")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("exclusive")
row_cells[1].text = str("Exclusive")
row_cells[2].text = str("Dimension")
row_cells[3].text = str("AUTO_GEN")
row_cells = table.add_row().cells
row_cells[0].text = str("large_image")
row_cells[1].text = str("p_large_image")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("small_image")
row_cells[1].text = str("p_small_image")
row_cells[2].text = str("Property")
row_cells[3].text = str("N/A")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=5)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Adapter Name"
hdr_cells[1].text = "Type"
hdr_cells[2].text = "Class"
hdr_cells[3].text = "Class Path/File Name"
hdr_cells[4].text = "Pass Throughs"
row_cells = table.add_row().cells
row_cells[0].text = str("LoadMainData")
row_cells[1].text = str("Delimited(\t)")
row_cells[2].text = str("N/A")
row_cells[3].text = str("items.txt")
row_cells[4].text = str("N/A")
row_cells = table.add_row().cells
row_cells[0].text = str("LoadMainAttributes")
row_cells[1].text = str("Delimited(\t)")
row_cells[2].text = str("N/A")
row_cells[3].text = str("attributes.txt")
row_cells[4].text = str("N/A")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=2)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "CacheMainAttributes"
hdr_cells[1].text = "[Sources]"
row_cells = table.add_row().cells
row_cells[0].text = str("LoadMainData")
row_cells[1].text = str("[Sources]")
row_cells = table.add_row().cells
row_cells[0].text = str("JoinAttributesToMain")
row_cells[1].text = str("[Assembler Name]")
row_cells = table.add_row().cells
row_cells[0].text = str("LEFT_JOIN")
row_cells[1].text = str("[Join Type]")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=4)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Cache Name"
hdr_cells[1].text = "General"
hdr_cells[2].text = "Sources"
hdr_cells[3].text = "Record Index"
row_cells = table.add_row().cells
row_cells[0].text = str("CacheMainAttributes")
row_cells[1].text = str("-1(Combine Recs)")
row_cells[2].text = str("FlattenMainAttributes")
row_cells[3].text = str("unique_id")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Properties/Dimensions"
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=3)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Manipulator Name"
hdr_cells[1].text = "Record Source"
hdr_cells[2].text = "Manipulations"
row_cells = table.add_row().cells
row_cells[0].text = str("AddPrimaryDimManipulator")
row_cells[1].text = str("JoinAttributesToMain")
row_cells[2].text = str("No Comment Provided - Add Manually")
row_cells = table.add_row().cells
row_cells[0].text = str("FlattenMainAttributes")
row_cells[1].text = str("LoadMainAttributes")
row_cells[2].text = str("No Comment Provided - Add Manually")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "all"
row_cells = table.add_row().cells
row_cells[0].text = str("primary")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_days_added")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "p_group_id"
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Searchable Properties and Dimensions"
row_cells = table.add_row().cells
row_cells[0].text = str("primary")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sku")
row_cells = table.add_row().cells
row_cells[0].text = str("Category")
row_cells = table.add_row().cells
row_cells[0].text = str("p_name")
row_cells = table.add_row().cells
row_cells[0].text = str("Brand")
row_cells = table.add_row().cells
row_cells[0].text = str("Collection")
row_cells = table.add_row().cells
row_cells[0].text = str("Color")
row_cells = table.add_row().cells
row_cells[0].text = str("Sports")
row_cells = table.add_row().cells
row_cells[0].text = str("p_upc")
row_cells = table.add_row().cells
row_cells[0].text = str("p_keyword")
row_cells = table.add_row().cells
row_cells[0].text = str("category_top")
row_cells = table.add_row().cells
row_cells[0].text = str("p_unique_id")
row_cells = table.add_row().cells
row_cells[0].text = str("p_sku")
row_cells = table.add_row().cells
row_cells[0].text = str("p_upc")
row_cells = table.add_row().cells
row_cells[0].text = str("Category")
row_cells = table.add_row().cells
row_cells[0].text = str("p_name")
row_cells = table.add_row().cells
row_cells[0].text = str("Brand")
row_cells = table.add_row().cells
row_cells[0].text = str("p_keyword")
row_cells = table.add_row().cells
row_cells[0].text = str("p_description_short")
row_cells = table.add_row().cells

document.add_page_break()
table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "p_price_sort"
row_cells = table.add_row().cells
row_cells[0].text = str("p_is_new")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_total_units_sold")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_profit_margin")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_sales_velocity")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_days_added")
row_cells = table.add_row().cells
row_cells[0].text = str("p_metric_inventory")
row_cells = table.add_row().cells

document.add_page_break()
document.add_page_break()
table = document.add_table(rows=1, cols=1)
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "p_description_short"
row_cells = table.add_row().cells
row_cells[0].text = str("p_sku")
row_cells = table.add_row().cells
row_cells[0].text = str("p_upc")
row_cells = table.add_row().cells

document.add_page_break()

document.add_page_break()

document.save("C:/Daniel/techSpectoDoc/techspecdoc.docx")